tplProjectName: mobilebuilder_tpl_8_0_0_ngx
â†“Menu [ngx.components.UIDynamicMenu-1604074900896]: ğŸ— mobileMenus/Menu.yaml
â†“SharedAction [ngx.components.UIActionStack-1620306204531]: ğŸ— mobileSharedActions/SharedAction.yaml
â†“initAndCreate [ngx.components.UIActionStack-1620306642547]: ğŸ— mobileSharedActions/initAndCreate.yaml
â†“initOpenTok [ngx.components.UIActionStack-1620306731231]: ğŸ— mobileSharedActions/initOpenTok.yaml
â†“modalVideoCall [ngx.components.UIActionStack-1620307352727]: ğŸ— mobileSharedActions/modalVideoCall.yaml
â†“disconnectFromSession [ngx.components.UIActionStack-1620744198968]: ğŸ— mobileSharedActions/disconnectFromSession.yaml
â†“VonageVideo [ngx.components.UISharedRegularComponent-1604074988538]: ğŸ— mobileSharedComponents/VonageVideo.yaml
â†“SessionsPage [ngx.components.PageComponent-1604074906869]: ğŸ— mobilePages/SessionsPage.yaml
â†“VideoPagePublish [ngx.components.PageComponent-1604828089911]: ğŸ— mobilePages/VideoPagePublish.yaml
â†“VideoPageSubscribe [ngx.components.PageComponent-1604935551023]: ğŸ— mobilePages/VideoPageSubscribe.yaml
â†“AskSessionPage [ngx.components.PageComponent-1604829479954]: ğŸ— mobilePages/AskSessionPage.yaml
â†“Page [ngx.components.PageComponent-1620308534347]: ğŸ— mobilePages/Page.yaml