tplProjectName: mobilebuilder_tpl_8_0_0_ngx
â†“Menu [ngx.components.UIDynamicMenu-1604074900896]: ğŸ— mobileMenus/Menu.yaml
â†“VonageVideo [ngx.components.UISharedComponent-1604074988538]: ğŸ— mobileSharedComponents/VonageVideo.yaml
â†“SessionsPage [ngx.components.PageComponent-1604074906869]: ğŸ— mobilePages/SessionsPage.yaml
â†“VideoPagePublish [ngx.components.PageComponent-1604828089911]: ğŸ— mobilePages/VideoPagePublish.yaml
â†“VideoPageSubscribe [ngx.components.PageComponent-1604935551023]: ğŸ— mobilePages/VideoPageSubscribe.yaml
â†“AskSessionPage [ngx.components.PageComponent-1604829479954]: ğŸ— mobilePages/AskSessionPage.yaml